# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: build-firmware-wireguard

on:
  workflow_dispatch:

jobs:
  build:
    #if: false #一時的に無効化
    runs-on: ubuntu-24.04

    steps:
    - name: checkout this
      uses: actions/checkout@v4
    - name: checkout micropython
      uses: actions/checkout@v4
      with:
        repository: micropython/micropython
        path: micropython
        ref: v1.23.0 #https://github.com/micropython/micropython/tree/v1.23.0/ports/esp32
    - name: checkout esp-idf
      uses: actions/checkout@v4
      with:
        repository: espressif/esp-idf
        path: esp-idf
        ref: v5.0.4
        #change from https://github.com/micropython/micropython/tree/master/ports/esp32#setting-up-esp-idf-and-the-build-environment
        # to https://github.com/micropython/micropython/blob/master/tools/ci.sh#L119
        submodules: recursive
    - name: checkout WireGuard-ESP32-Arduino
      uses: actions/checkout@v4
      with:
        repository: ciniml/WireGuard-ESP32-Arduino
        path: WireGuard
    - name: install dependencies tools
      # https://micropython-docs-ja.readthedocs.io/ja/latest/develop/gettingstarted.html#required-dependencies
      # https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/get-started/linux-macos-setup.html
      run: |
        sudo apt update
        sudo apt install build-essential libffi-dev git pkg-config
        sudo apt install wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
    - name: install esp-idf
      run: |
        cd ${GITHUB_WORKSPACE}/esp-idf
        ./install.sh >/dev/null
    - name: patch
      run: |
        sed -i 's/static void mul(fe out, const fe a, const fe b, unsigned nb) {/static void mul(fe out, const fe a, const limb_t b[], unsigned nb) {/' ${GITHUB_WORKSPACE}/WireGuard/src/crypto/refc/x25519.c
        sed -i '/wireguard_create_cookie_reply/a void handshake_destroy(struct wireguard_handshake *handshake);' ${GITHUB_WORKSPACE}/WireGuard/src/wireguard.h
        sed -i 's/#include "tcpip_adapter.h"/#include "esp_netif.h"/' ${GITHUB_WORKSPACE}/WireGuard/src/wireguardif.c
        sed -i '/esp_netif.h/a #include "esp_netif_net_stack.h"' ${GITHUB_WORKSPACE}/WireGuard/src/wireguardif.c
        sed -i 's/tcpip_adapter_get_netif(TCPIP_ADAPTER_IF_STA, &underlying_netif);/underlying_netif=esp_netif_get_netif_impl(esp_netif_get_handle_from_ifkey("WIFI_STA"));/' ${GITHUB_WORKSPACE}/WireGuard/src/wireguardif.c
        sed -i 's/#include "esp32-hal-log.h"//' ${GITHUB_WORKSPACE}/WireGuard/src/wireguardif.c
        sed -i '/^\t*log_/d' ${GITHUB_WORKSPACE}/WireGuard/src/wireguardif.c
        sed -i 's/%08x/%08lx/g' ${GITHUB_WORKSPACE}/WireGuard/src/wireguardif.c
        sed -i '70,76d' ${GITHUB_WORKSPACE}/WireGuard/src/WireGuard.cpp
        sed -i '/^\t*log_/d' ${GITHUB_WORKSPACE}/WireGuard/src/WireGuard.cpp
        sed -i 's/#include "esp32-hal-log.h"//' ${GITHUB_WORKSPACE}/WireGuard/src/WireGuard.cpp
        echo -e "set(MICROPY_BOARD_FLAGS\n    -DLWIP_DEBUG=1\n)" >> ${GITHUB_WORKSPACE}/micropython/ports/esp32/boards/ESP32_GENERIC_C3/mpconfigboard.cmake
        cat ${GITHUB_WORKSPACE}/micropython/ports/esp32/boards/ESP32_GENERIC_C3/mpconfigboard.cmake
    - name: build firmware
      # https://github.com/micropython/micropython/tree/v1.23.0/ports/esp32#setting-up-esp-idf-and-the-build-environment
      run: |
        cd ${GITHUB_WORKSPACE}/esp-idf
        source export.sh
        cd ${GITHUB_WORKSPACE}/micropython
        make -C mpy-cross
        cd ports/esp32
        make submodules
        make BOARD=ESP32_GENERIC_C3 USER_C_MODULES=${GITHUB_WORKSPACE}/WireGuard-micropython.cmake
    - name: save firmware
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: firmware
        path: micropython/ports/esp32/build-ESP32_GENERIC_C3/
  ls:
    runs-on: ubuntu-24.04
    if: false #一時的に無効化
    steps:
      - name: checkout this
        uses: actions/checkout@v4
      - name: checkout WireGuard-ESP32-Arduino
        uses: actions/checkout@v4
        with:
          repository: ciniml/WireGuard-ESP32-Arduino
          path: WireGuard  
      - name: ls
        run: |
          pwd
          ls -la
          ls -la ${GITHUB_WORKSPACE}/WireGuard/
